// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const delete = `-- name: Delete :one
DELETE FROM users
WHERE id = $1
RETURNING id, first_name, last_name, biography
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, delete, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Biography,
	)
	return i, err
}

const findAll = `-- name: FindAll :many
SELECT id, first_name, last_name, biography
FROM users
`

func (q *Queries) FindAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Biography,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findById = `-- name: FindById :one
SELECT id, first_name, last_name, biography
FROM users
WHERE id = $1
`

func (q *Queries) FindById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Biography,
	)
	return i, err
}

const insert = `-- name: Insert :one
INSERT INTO users (first_name, last_name, biography)
VALUES ($1, $2, $3)
RETURNING id, first_name, last_name, biography
`

type InsertParams struct {
	FirstName string
	LastName  string
	Biography string
}

func (q *Queries) Insert(ctx context.Context, arg InsertParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insert, arg.FirstName, arg.LastName, arg.Biography)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Biography,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE users
SET first_name = $2,
    last_name  = $3,
    biography  = $4
WHERE id = $1
RETURNING id, first_name, last_name, biography
`

type UpdateParams struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Biography string
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Biography,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Biography,
	)
	return i, err
}
